GET http://localhost:3001/ HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/ HTTP/1.1
Content-Type: application/json 

{
    "firstName": "Shreaysu",
    "lastName": "Bhagwat",
    "phoneNumber": "4036047756"
}

###

PUT http://localhost:3001/2 HTTP/1.1
Content-Type: application/json 

{
    "firstName": "Shreaysu"
}

###

DELETE http://localhost:3001/1 HTTP/1.1
Content-Type: application/json 

